### ISSUE TITLE
Semantic Class Labels

### ISSUE THREAD

**Issue by jmount1992** [unmannedlab/ROOAD#1]
Hi,

Thanks for releasing yet another great dataset. We were wondering if you plan to release semantic class labels, at least for some of the images, similar to the Rellis-3D Dataset?

Thanks!

**Comment by gchustz** [comment]
At the moment, we are not focused on semantic labelling for this dataset as this was mainly focused on VIO implementation.

However, our work with semantic labelling is not finished so it is a possibility in the near future.
